name: Copy Modified Files to Frontend

on:
  push:
    branches:
      - main

jobs:
  copy-modified-files:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Identify Modified Files
      id: modified-files
      run: |
        echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"
        
    - name: Copy Modified Files to Frontend
      run: |
        for file in ${{ steps.modified-files.outputs.files }}; do
          if [[ "$file" == src/* ||
                "$file" == src/**/* ||
                "$file" == src/pages/**/* ||
                "$file" == src/assets/**/* ||
                "$file" == src/styles/**/* ||
                "$file" == src/components/**/* ||
                "$file" == public/* ||
                "$file" == public/**/* ||
                "$file" == public/images/**/* ||
                "$file" == public/images/assets/**/* ||
                "$file" == public/images/profiles/**/* ]]; then
            cp "$file" "frontend/$file"
          fi
        done
